'use strict';

// prettier-ignore
const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const form = document.querySelector('.form');
const containerWorkouts = document.querySelector('.workouts');
const inputType = document.querySelector('.form__input--type');
const inputDistance = document.querySelector('.form__input--distance');
const inputDuration = document.querySelector('.form__input--duration');
const inputCadence = document.querySelector('.form__input--cadence');
const inputElevation = document.querySelector('.form__input--elevation');

let map,mapEvent;

if(navigator.geolocation){
    navigator.geolocation.getCurrentPosition(function(position){

        const {latitude} = position.coords
        const {longitude} = position.coords
        console.log(`https://www.google.com/maps/@${latitude},${longitude}`);

        //یک سری متد داره
        //L is a nameSpace for sth
        const coords = [latitude,longitude]
        //because setView is get an array we store in an aaray and then passed it
         map = L.map('map').setView(coords, 15 );

// L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker(coords).addTo(map)
    .bindPopup('A pretty CSS popup.<br> Easily customizable.')
    .openPopup();

    

    //map is a obj generated by leaflet
    //on is a event of leaflet

    //handling clicks on map
    map.on('click',function(mapE){
        mapEvent = mapE;
        form.classList.remove('hidden')
        inputDistance.focus()
    });
},function(){
        alert("can't get location")
    })
    }

    form.addEventListener('submit',function(e){
        e.preventDefault()
        //clear input fields
        inputDistance.value=''
inputDuration.value=''
inputCadence.value=''
inputElevation.value=''

        // /display the marker
        const {lat,lng}=mapEvent.latlng
// marker create
// add marker to map
// create a pop up

L.marker([lat,lng])
.addTo(map)
    .bindPopup(L.popup({maxWidth:250,minWidth:100,autoClose:false,closeOnClick:false , className:'running-popup'}))
    .setPopupContent('workout')
    .openPopup();
    })

    inputType.addEventListener('change',function(){
        inputElevation.closest('.form__row').classList.toggle('form__row--hidden')
        inputCadence.closest('.form__row').classList.toggle('form__row--hidden')
    })